function [sTracks]=createStoreTracks()
% create an empty array of tracks
        sTracks = struct(...
            'id', {}, ...
            'data',{},...
            'trackedFrames', 1,...
            'predictedData',{});
end
